[CHORE (Activate)]: run activation pipeline for dev - 2026-05-01 16:30:06

diff --git a/.github/workflows/add_new_app.yml b/.github/workflows/add_new_app.yml
--- a/.github/workflows/add_new_app.yml
+++ b/.github/workflows/add_new_app.yml
@@ -30,6 +30,51 @@ jobs:
           token: ${{ steps.app-token.outputs.token }}
           fetch-depth: 0
 
+      - name: Install jq
+        run: |
+          set -euo pipefail
+          sudo apt-get update
+          sudo apt-get install -y jq
+
+      - name: Get Current Env
+        run: |
+          STATE_FILE="gitops/state/current.json"
+          if [[ ! -f "$STATE_FILE" || ! -s "$STATE_FILE" ]]; then
+            echo "❌ State File: $STATE_FILE is Missing or Empty. Cannot Decipher the appropriate ENV to update"
+            exit 1
+          fi
+
+          CURRENT_RUN_ID="${{ github.event.workflow_run.id }}"
+          STATE_RUN_ID=$(jq -r '.run_id' gitops/state/current.json)
+          STATE_TS=$(jq -r '.timestamp' gitops/state/current.json)
+
+          if [[ "$STATE_RUN_ID" != "$CURRENT_RUN_ID" ]]; then
+            echo "⚠️ State file is stale or from another run"
+            echo "State: $STATE_RUN_ID | Current: $CURRENT_RUN_ID"
+            exit 1
+          fi
+
+          MAX_AGE=18000
+          NOW_TS=$(date -u +%Y-%m-%dT%H:%M:%SZ)
+          STATE_EPOCH=$(date -d "$STATE_TS" +%s)
+          NOW_EPOCH=$(date -d "$NOW_TS" +%s)
+          echo "State Timestamp: $STATE_TS"
+          echo "Now Timestamp  : $NOW_TS"
+          AGE=$((NOW_EPOCH - STATE_EPOCH))
+
+          if (( AGE > MAX_AGE )); then
+            echo "❌ State file too old ($AGE sec)"
+            exit 1
+          fi
+
+          STATE_ENV=$(jq -r '.env' gitops/state/current.json)
+          if [[ -z "$STATE_ENV" || "$STATE_ENV" == "null" ]]; then
+            echo "❌ ENV Source from state file Empty"
+            exit 1
+          fi
+
+          echo "ENV=$STATE_ENV" >> GITHUB_ENV
+
       - name: Install dependencies
         run: |
           set -euo pipefail
@@ -67,10 +112,11 @@ jobs:
       - name: Create values + inject vars + ingress registration
         run: |
           set -euo pipefail
-          APP_LIST="$(find gitops/registry -name "*.json" | wc -l)"
+          ENV="${{ env.ENV }}"
+          APP_LIST="$(find gitops/registry/$ENV -name "*.json" | wc -l)"
           echo "Number of Apps Found: $APP_LIST"
 
-          for file in $(find gitops/registry -name "*.json"); do
+          for file in $(find gitops/registry/$ENV -name "*.json"); do
             echo ""
             echo "================================================"
             echo "Processing metadata: $file"
@@ -107,9 +153,9 @@ jobs:
             # Register app in shared ingress
             ####################################################
             echo "Registering ingress route..."
-            bash scripts/register_new_svc.sh "$SERVICE"
+            bash scripts/register_new_svc.sh "$SERVICE" "$ENV"
 
-            echo "✅ Provision complete for: $SERVICE"
+            echo "✅ Provision complete for: $SERVICE - $ENV"
           done
 
       - name: Validate GitOps structure
@@ -136,4 +182,4 @@ jobs:
           git commit -m "[ADD-APP] ${DATE} provision new application(s)"
           git push
 
-          echo "✅ New app provisioning committed successfully"
+          echo "✅ New app provisioning committed successfully for $ENV"
