[CHORE (Activate)]: run activation pipeline for dev - 2026-05-02 14:56:09

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -324,8 +324,7 @@ jobs:
         env:
           ENV: ${{ needs.build.outputs.env }}
         run: |
-          rm -rf gitops/registry
-          echo " Old registry removed, New one recreating.."
+          mv gitops/registry temp
           NEW_DIR="gitops/registry/$ENV"
           mkdir -p  "$NEW_DIR"
           echo "NEW_DIR=$NEW_DIR" >> $GITHUB_ENV
@@ -363,6 +362,22 @@ jobs:
             cat "$file"
             echo
           done
+
+      - name: Delete Old Registry
+        env:
+        run: |
+          for each in $(find artifacts/. -type f -name "*.json" ); then
+            bash scripts/validate_registry.sh "$each"
+          fi
+
+          if [[ "$RESULT" == "success" ]]; then
+            rm -rf temp
+            rm -rf artifacts
+            echo "✅ Old registry removed.."
+          else
+            echo "❌ Registry files from downloaded artifacts failed structural Validations.. Require manual check"
+            exit 1
+          fi
 
       - name: Create State file Metadata for Downstream
         env:
