[CHORE (Activate)]: run activation pipeline for dev - 2026-05-03 14:16:36

diff --git a/.github/workflows/get_deploy_artifacts.yml b/.github/workflows/get_deploy_artifacts.yml
--- a/.github/workflows/get_deploy_artifacts.yml
+++ b/.github/workflows/get_deploy_artifacts.yml
@@ -27,9 +27,13 @@ jobs:
             --status success \
             --limit 1 \
             --json databaseId \
-            --jq '.[0].databaseId')
+            --jq '.[0].databaseId'
+          )
 
-          [[ -n "$RUN_ID" ]] || { echo "❌ Run_id Not found" && exit 1 }
+          if [[ -z "$RUN_ID" ]]; then
+             echo "❌ Run_id Not found"
+             exit 1
+          fi
           echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
 
       - name: List artifacts for run
@@ -48,7 +52,10 @@ jobs:
         run: |
           set -euo pipefail
           DIR="artifacts/registry-user_app"
-          [[ -d "$DIR" ]] || { echo "❌ $DIR Not found" && exit 1 }
+          if [[ ! -d "$DIR" ]]; then
+            echo "❌ $DIR Not found"
+            exit 1
+          fi
           echo "Listing files..."
           find "$DIR" -type f
           while IFS= read -r each; do
