[CHORE (Activate)]: run activation pipeline for dev - 2026-05-04 13:40:49

diff --git a/.github/workflows/setup_argocd.yml b/.github/workflows/setup_argocd.yml
--- a/.github/workflows/setup_argocd.yml
+++ b/.github/workflows/setup_argocd.yml
@@ -154,4 +154,17 @@ jobs:
         env:
           ENV: "${{ github.event.inputs.env }}"
           DOMAIN: "${{ secrets.DOMAIN }}"
-        run: bash scripts/sync_route53.sh
+        run: |
+          set -euio pipefail
+          for i in {1..6}; do
+            echo "Setting up route53 for Domain if new..."
+            if bash scripts/sync_route53.sh; then
+              echo "✅ Success on attempt $i"
+              break
+            else
+              echo "ALB not ready yet, retrying..."
+              sleep 5
+            fi
+            echo "❌ Route53 sync failed after retries"
+            exit 1
+          done
