AUTO-COMMIT on 2026-04-26 23:45:20

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -67,7 +67,6 @@ jobs:
         run: |
           set -e
 
-          REG_FILE="gitops/registry/services.yaml"
           for file in $(find artifacts -name "*.json"); do
             SERVICE=$(jq -r .service "$file")
             IMAGE=$(jq -r .image "$file")
@@ -78,25 +77,14 @@ jobs:
               exit 1
             fi
 
-            EXISTS=$(yq e ".services | has(\"$SERVICE\")" "$REG_FILE")
-            if [ "$EXISTS" != "true" ]; then
-              echo "Service $SERVICE not registered"
+            FILE="gitops/envs/$ENV/$SERVICE/values.yaml"
+            if [[ ! -f "$FILE" ]]; then
+              echo "Values File for ${SERVICE}-${ENV} NOT Found"
               exit 1
             fi
 
-            FILE=$(yq e ".services.$SERVICE.values.$ENV" "$REG_FILE")
-            if [ "$FILE" = "null" ] || [ -z "$FILE" ]; then
-              echo "No env mapping for $SERVICE in $ENV"
-              exit 1
-            fi
-
-            echo "Updating $SERVICE ($ENV)"
+            echo "Updating ${SERVICE}-${ENV}"
             echo "Target file: $FILE"
-
-            if [ ! -f "$FILE" ]; then
-              echo "Missing GitOps file: $FILE"
-              exit 1
-            fi
 
             yq e ".image.repository = strenv(IMAGE)" -i "$FILE"
 
@@ -104,10 +92,14 @@ jobs:
 
       - name: Commit changes
         run: |
+          DATE=$(date +"%Y-%m-%d_%H-%M-%S")
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
 
           git add .
-          git diff --exit-code
-          git commit -m "gitops update from build pipeline" || exit 0
+          git diff --quiet && {
+            echo "No changes detected"
+            exit 0
+          }
+          git commit -m "[$DATE] Gitops Update from build pipeline" || exit 0
           git push
